controller_list:
 - name: robot_arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - base_link2rotary_plate
     - rotary_plate2upper_arm
     - upper_arm2elbow
     - elbow2forearm
     - forearm2wrist
     - wrist2hand
